'use strict';

module.exports = {
    apple: require('./apple.js')
    /*,
    balance: require('/'),
    bjstart: require('/'),
    bp: require('/'),
    cas: require('/'),
    config: require('/'),
    debug: require('/'),
    density: require('/'),
    eval: require('/'),
    fortune: require('/'),
    gayname: require('/'),
    geoip: require('/'),
    heilhitler: require('/'),
    help: require('/'),
    jew: require('/'),
    kek: require('/'),
    kekget: require('/'),
    killallevals: require('/'),
    killeval: require('/'),
    lenny: require('/'),
    mass: require('/'),
    math: require('/'),
    medchem: require('/'),
    mol: require('/'),
    molar: require('/'),
    monopoly: require('/'),
    mp: require('/'),
    mw: require('/'),
    n: require('/'),
    nigger: require('/'),
    nignog: require('/'),
    os: require('/'),
    poopoo: require('/'),
    prop: require('/'),
    rpg: require('/'),
    shout: require('/'),
    sim: require('/'),
    sponge: require('/'),
    start: require('/'),
    sym: require('/'),
    synonym: require('/'),
    terribleweebcancer: require('/'),
    twat: require('/'),
    volume: require('/'),
    year: require('/')
    */
};
